// ── Watchdog: who watches the watchman ────────────────────────────────────────
//
// Every check in this estate runs on GitHub Actions: Upptime's uptime.yml, the
// social crons, the token-expiry alert, the nightly worker drift check. That
// makes GitHub Actions a single point of silence. If a schedule stops firing —
// disabled after 60 days of repository inactivity, a run stuck `waiting` on an
// approval gate holding its concurrency group, a billing lapse — then every
// check stops running, nothing turns red, and the status page keeps showing
// green because it is also generated by the thing that died.
//
// Upptime cannot close this: its own "Status Page" check is inside Upptime.
//
// So the watchman lives on a different platform. This module runs on a
// Cloudflare cron trigger (Cloudflare's scheduler, not GitHub's) and alerts by
// Cloudflare Email Sending (not GitHub notifications). The two platforms watch
// each other:
//
//   GitHub → Cloudflare: monitor-watchdog.yml probes /api/health, so a dead
//                        worker surfaces as a failed workflow and an issue.
//   Cloudflare → GitHub: this scheduled handler alerts when the watchdog
//                        workflow stops checking in, so a dead GitHub scheduler
//                        surfaces as an email.
//
// Neither platform can fail silently by taking its own monitor down with it.
//
// It also sends a weekly proof-of-life email. That inverts the failure mode for
// the alerting channel itself: if the crisis/alert email path breaks — a
// revoked binding, an unverified destination, a DNS change — no alert can ever
// arrive, and absence of alerts is indistinguishable from "everything is fine".
// A heartbeat email that is SUPPOSED to arrive weekly makes silence itself the
// signal.

import type { EmailSender } from './email';
import { sendOpsEmail } from './email';

export interface WatchdogEnv {
  SOCIAL: KVNamespace;
  CRISIS_EMAIL?: EmailSender;
  CRISIS_ALERT_FROM?: string;
  CRISIS_ALERT_TO?: string;
}

/** KV prefix for check-ins from external pipelines (GitHub Actions workflows). */
export const EXTERNAL_HEARTBEAT_PREFIX = 'heartbeat:external:';

/** KV prefix for per-source alert cooldowns. */
const ALERT_COOLDOWN_PREFIX = 'watchdog-alerted:';

/** KV key holding when the last weekly proof-of-life email went out. */
const PROOF_OF_LIFE_KEY = 'watchdog-proof-of-life';

/**
 * One email per source per 24h while a source stays stale.
 *
 * Without a cooldown an hourly scheduled handler would send 24 identical emails
 * a day for one dead workflow, which is how an alert channel becomes a filter
 * rule. Long enough to be quiet, short enough that the reminder recurs until
 * someone fixes it.
 */
export const ALERT_COOLDOWN_MS = 24 * 60 * 60_000;

/** Weekly proof-of-life cadence. */
export const PROOF_OF_LIFE_INTERVAL_MS = 7 * 24 * 60 * 60_000;

export interface ExternalSource {
  /** Heartbeat name; the KV key suffix and the identifier callers POST. */
  name: string;
  /** Human description used in the alert email. */
  description: string;
  /**
   * How long after the last check-in this source is considered dead.
   *
   * Set this to several times the source's nominal cadence. These are alerts
   * that wake a human by email, so tolerating a couple of missed runs is the
   * right trade — the failure being caught (a schedule that has stopped
   * entirely) does not resolve itself, so catching it a few hours late costs
   * nothing, while a tight threshold guarantees false alarms from GitHub's
   * best-effort scheduler.
   */
  staleAfterMs: number;
}

/**
 * External pipelines expected to check in. Adding an entry here is what makes a
 * workflow's silence detectable — the workflow must POST
 * /api/watchdog/heartbeat with a matching `name`.
 */
export const EXTERNAL_SOURCES: ExternalSource[] = [
  {
    name: 'monitor-watchdog',
    description: 'monitor-watchdog.yml (hourly: Upptime freshness, disabled schedules, stuck runs)',
    // Hourly cadence, alert after 4 missed runs.
    staleAfterMs: 4 * 60 * 60_000,
  },
  {
    name: 'upptime',
    description: "Upptime's uptime.yml (every 5 min: all endpoint checks and the status page)",
    // Every 5 minutes, but the check-in is relayed hourly by monitor-watchdog,
    // so this threshold has to clear the RELAY cadence, not the 5-minute one.
    staleAfterMs: 4 * 60 * 60_000,
  },
];

export interface ExternalHeartbeatRecord {
  at: string;
  atEpoch: number;
  /** Optional free-text detail from the caller, echoed in alerts. */
  detail?: string;
}

/** Record a check-in from an external pipeline. Returns false for unknown names. */
export async function recordExternalHeartbeat(
  kv: KVNamespace,
  name: string,
  detail: string | undefined,
  now: number = Date.now(),
): Promise<boolean> {
  if (!EXTERNAL_SOURCES.some((s) => s.name === name)) return false;
  const record: ExternalHeartbeatRecord = {
    at: new Date(now).toISOString(),
    atEpoch: now,
    ...(detail ? { detail } : {}),
  };
  await kv.put(`${EXTERNAL_HEARTBEAT_PREFIX}${name}`, JSON.stringify(record));
  // A source that checks in again has recovered; drop the cooldown so the NEXT
  // outage alerts immediately instead of being suppressed by a stale marker.
  await kv.delete(`${ALERT_COOLDOWN_PREFIX}${name}`).catch(() => {});
  return true;
}

export interface ExternalStatus {
  name: string;
  description: string;
  lastCheckIn: string | null;
  ageSeconds: number | null;
  staleAfterSeconds: number;
  stale: boolean;
}

/**
 * Classify every external source.
 *
 * A missing record is stale for the same reason it is in heartbeat.ts: a
 * pipeline that has never checked in is precisely the outage being detected.
 */
export async function readExternalHeartbeats(
  kv: KVNamespace,
  now: number = Date.now(),
): Promise<ExternalStatus[]> {
  const statuses: ExternalStatus[] = [];

  for (const source of EXTERNAL_SOURCES) {
    const status: ExternalStatus = {
      name: source.name,
      description: source.description,
      lastCheckIn: null,
      ageSeconds: null,
      staleAfterSeconds: Math.round(source.staleAfterMs / 1000),
      stale: true,
    };

    try {
      const raw = await kv.get(`${EXTERNAL_HEARTBEAT_PREFIX}${source.name}`);
      if (raw) {
        const record = JSON.parse(raw) as Partial<ExternalHeartbeatRecord>;
        if (typeof record.atEpoch === 'number' && Number.isFinite(record.atEpoch)) {
          const ageMs = Math.max(0, now - record.atEpoch);
          status.lastCheckIn = typeof record.at === 'string' ? record.at : new Date(record.atEpoch).toISOString();
          status.ageSeconds = Math.round(ageMs / 1000);
          status.stale = ageMs > source.staleAfterMs;
        }
      }
    } catch (e) {
      console.error(`External heartbeat read failed for '${source.name}': ${e instanceof Error ? e.message : String(e)}`);
    }

    statuses.push(status);
  }

  return statuses;
}

function formatAge(ageSeconds: number | null): string {
  if (ageSeconds === null) return 'never';
  const hours = Math.floor(ageSeconds / 3600);
  if (hours < 1) return `${Math.round(ageSeconds / 60)} minutes ago`;
  if (hours < 48) return `${hours} hours ago`;
  return `${Math.floor(hours / 24)} days ago`;
}

/**
 * The scheduled sweep. Alerts on stale sources (respecting the cooldown) and
 * sends the weekly proof-of-life email.
 *
 * Never throws: a scheduled handler that throws is retried and logged, but the
 * useful outcome here is "do as much of the sweep as possible and record what
 * happened", not "fail loudly to nobody".
 */
export async function runWatchdogSweep(
  env: WatchdogEnv,
  now: number = Date.now(),
): Promise<{ checked: number; stale: string[]; alertsSent: number; proofOfLifeSent: boolean }> {
  const statuses = await readExternalHeartbeats(env.SOCIAL, now);
  const stale = statuses.filter((s) => s.stale);
  let alertsSent = 0;

  for (const source of stale) {
    const cooldownKey = `${ALERT_COOLDOWN_PREFIX}${source.name}`;
    try {
      if (await env.SOCIAL.get(cooldownKey)) continue;

      const lines = [
        `Monitoring source '${source.name}' has stopped checking in.`,
        '',
        `Source:        ${source.description}`,
        `Last check-in: ${source.lastCheckIn ?? 'never'} (${formatAge(source.ageSeconds)})`,
        `Threshold:     ${Math.round(source.staleAfterSeconds / 3600)} hours`,
        '',
        'This alert comes from a Cloudflare cron trigger, deliberately not from',
        'GitHub Actions — so it still fires when GitHub Actions is the thing that',
        'has stopped. Likely causes, most common first:',
        '',
        '  1. The scheduled workflow was disabled after 60 days of repository',
        '     inactivity (GitHub does this silently). Re-enable it in the Actions',
        '     tab, or push any commit to the repo.',
        '  2. A run is stuck in `waiting` on an approval gate and is holding its',
        '     concurrency group, so no later run can start. Cancel the stale run.',
        '  3. The workflow is failing before it reaches the check-in step.',
        '',
        `Checked at ${new Date(now).toISOString()}.`,
      ];

      const sent = await sendOpsEmail(env, `[MONITORING] ${source.name} has stopped checking in`, lines.join('\n'));
      if (sent) {
        alertsSent++;
        // Cooldown is written only on a SUCCESSFUL send. Writing it on failure
        // would suppress retries of an alert that never reached anyone.
        await env.SOCIAL.put(cooldownKey, new Date(now).toISOString(), {
          expirationTtl: Math.round(ALERT_COOLDOWN_MS / 1000),
        });
      }
    } catch (e) {
      console.error(`Watchdog alert failed for '${source.name}': ${e instanceof Error ? e.message : String(e)}`);
    }
  }

  const proofOfLifeSent = await maybeSendProofOfLife(env, statuses, now);

  return { checked: statuses.length, stale: stale.map((s) => s.name), alertsSent, proofOfLifeSent };
}

/**
 * Send the weekly proof-of-life email if one is due.
 *
 * This is the only check on the alerting channel itself. Everything else in the
 * estate alerts by exception, so a broken email path is invisible: no alerts
 * arrive, and that looks exactly like health. A message that is supposed to
 * arrive every week turns silence into evidence.
 */
async function maybeSendProofOfLife(
  env: WatchdogEnv,
  statuses: ExternalStatus[],
  now: number,
): Promise<boolean> {
  try {
    const raw = await env.SOCIAL.get(PROOF_OF_LIFE_KEY);
    const lastEpoch = raw ? Number(raw) : NaN;
    // On first run there is no marker. Record the timestamp WITHOUT sending, so
    // a deploy doesn't fire an immediate email and the cadence starts clean.
    if (!Number.isFinite(lastEpoch)) {
      await env.SOCIAL.put(PROOF_OF_LIFE_KEY, String(now));
      return false;
    }
    if (now - lastEpoch < PROOF_OF_LIFE_INTERVAL_MS) return false;

    const body = [
      'Weekly monitoring proof-of-life.',
      '',
      'You are receiving this because the alerting path works. If this email',
      'ever stops arriving, treat that as the alert: either the watchdog cron',
      'has stopped or the email path itself has broken, and in both cases no',
      'failure alert could reach you either.',
      '',
      'Monitoring sources checked in:',
      ...statuses.map((s) => `  ${s.stale ? '✗' : '✓'} ${s.name} — last check-in ${formatAge(s.ageSeconds)}`),
      '',
      `Sent ${new Date(now).toISOString()} from the Cloudflare watchdog cron.`,
    ].join('\n');

    const sent = await sendOpsEmail(env, '[MONITORING] Weekly proof-of-life', body);
    // Only advance the clock on a successful send, so a transient failure
    // retries next tick instead of skipping a whole week.
    if (sent) await env.SOCIAL.put(PROOF_OF_LIFE_KEY, String(now));
    return sent;
  } catch (e) {
    console.error(`Proof-of-life send failed: ${e instanceof Error ? e.message : String(e)}`);
    return false;
  }
}
